backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/cms-pages/HomepageEn.md"
        label: "HomepageEn"
        name: "homepageEn"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepageEn-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
      - file: "src/cms-pages/HomepageDe.md"
        label: "HomepageDe"
        name: "homepageDe"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepageDe-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
      - file: "src/cms-pages/About.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}