export interface ProductStatistics {
  /**
   * @description the total revenue generated by the product (in smallest units)
   * @member {number} [totalRevenue]
   */
  totalRevenue?: number;

  /**
   * @member {string} [currency]
   * @description lowercase 3 letter currency code as defined by ISO-4217
   * @example: eur
   */
  currency?: string;

  /**
   * @description the revenue generated by the product within the current month (in smallest units)
   * @member {number} [totalRevenue]
   */
  currentRevenue?: number;

  /**
   * @member {number} [month]
   * @description number representing the month of the current revenue (0 - January, 1 - February, etc.)
   * @example: 2 (March)
   */
  revenueMonth?: number;

  /**
   * @member {number} [month]
   * @description count of currently active subscriptions
   */
  subscriptionCount?: number;

  /**
   * @description Average latency of the API calls of this Product
   */
  latencyAvg?: number;

  /**
   * @description Average success rate of the API calls of this Product
   */
  successRateAvg?: number;
}
